name: Sphinx

on:
  push: {}
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  doctest:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Sphinx Gallery Cache
      uses: actions/cache@v3
      env:
        cache-name: sphx-glry-doctest
      with:
        path: |
          tutorial/MNIST
          docs/source/tutorial
        key: py3.8-${{ env.cache-name }}-${{ hashFiles('tutorial/**/*') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document]

    - name: Output installed packages
      run: |
        pip freeze --all
    - name: Output dependency tree
      run: |
        pip install pipdeptree
        pipdeptree

    - name: Run Doctest
      run: |
        cd docs
        make doctest
